

.PHONY: all
all:
	@echo "Open README.md to get usage.";

.PHONY: run
run:
	@printf "";\
	python3 main.py


.PHONY: test
test:
	@printf "";\
	python3 classifiers/test.py

.PHONY: unittests
unittest:
	@printf "";\
	./unittests.sh	


.PHONY: label
label:
	@printf "";\
	python3 classifiers/labeller.py

.PHONY: train
train:
	@printf "";\
	python3 classifiers/train.py

.PHONY: evaluate
evaluate:
	@printf "";\
	python3 classifiers/evaluator.py


.PHONY: enter
enter:
	@printf "";\
	source env/bin/activate

.PHONY: exit
exit:
	@printf "";\
	deactivate


